# Generated by Django 4.0.1 on 2022-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stilltheory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tos_violation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
